# Sales Analysis
This notebook provides a comprehensive sales analysis using the dataset `dataset_supermarket_sales.csv`.

In [1]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv('sales_data.csv')

# 'yyyy-mm-dd'

# Convert 'Date' to datetime format
df['Date'] = pd.to_datetime(df['Date'])
# Extract hour from 'Time'
df['Hour'] = df['Time'].apply(lambda x: int(x.split(':')[0]))
df['Invoice ID01'] = df['Invoice ID'].apply(lambda x: int(x.split('-')[0]))

df.head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,cogs,Date,Time,Payment,Hour,Invoice ID01
0,860-79-0874,C,Chennai,Member,Female,Fashion accessories,99.30,9,49.65,1122.192223,993.0,2022-02-15,14:53,Credit card,14,860
1,687-47-8271,A,Trichy,Normal,Male,Fashion accessories,98.98,9,49.49,1118.575893,989.8,2022-08-02,16:20,Credit card,16,687
2,283-26-5248,C,Chennai,Member,Female,Food and beverages,98.52,9,49.26,1113.377420,985.2,2022-01-30,20:23,Ewallet,20,283
3,751-41-9720,C,Chennai,Normal,Male,Home and lifestyle,97.50,9,48.75,1101.850370,975.0,2022-12-01,16:18,Ewallet,16,751
4,303-96-2227,B,karur,Normal,Female,Home and lifestyle,97.38,9,48.69,1100.494246,973.8,2022-02-03,17:16,Ewallet,17,303

## 1. Descriptive Statistics

In [2]:
# Total Sales
total_sales = df['Total'].sum()
print(total_sales)

1334239.08429618

In [3]:
# Average Sales
average_sales = df['Total'].mean()

print(average_sales)

333.559771074045

In [4]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Total', 'cogs',
       'Date', 'Time', 'Payment', 'Rating', 'Hour', 'Invoice ID01'],
      dtype='object')

### Sales by Branch

In [5]:
# Sales by Branch
sales_by_branch = df.groupby('Branch')['Total'].sum()
print(sales_by_branch)

Branch
A    437615.922729
B    438459.296197
C    455556.956870
Name: Total, dtype: float64

In [6]:
sales_by_branch_gender = df.groupby(['Branch', 'Gender'])['Total'].sum()
print(sales_by_branch_gender)

Branch  Gender
A       Female    219128.163169
        Male      218487.759559
B       Female    218393.035476
        Male      220066.260721
C       Female    254062.385258
        Male      201494.571613
Name: Total, dtype: float64

In [7]:
sales_by_branch_gender = df.groupby(['Branch', 'Gender'])['Total'].agg(['sum', 'mean', 'count'])

print(sales_by_branch_gender)

                         sum        mean  count
Branch Gender
A      Female  219128.163169  341.853609    641
       Male    218487.759559  305.577286    715
B      Female  218393.035476  338.069714    646
       Male    220066.260721  323.626854    680
C      Female  254062.385258  357.331062    711
       Male    201494.571613  336.384928    599

In [15]:
df.groupby('Branch').agg({
    'Total': ['sum', 'mean'],
    'Quantity': 'sum',
    'Rating': 'mean',
    'Invoice ID': 'nunique'
})

                Total             Quantity    Rating Invoice ID
                  sum        mean      sum      mean    nunique
Branch
A       437615.922729  322.725607     7411  7.170999        340
B       438459.296197  330.663119     7273  6.962403        332
C       455556.956870  347.753402     7320  7.221655        328

### Sales by City

In [ ]:
# Sales by City
sales_by_city = df.groupby('City')['Total'].sum()
sales_by_city

City
Chennai    456781.046870
Trichy     438734.592729
karur      438723.444697
Name: Total, dtype: float64

### Sales by Customer Type

In [8]:
# Sales by Customer Type
sales_by_customer_type = df.groupby('Customer type')['Total'].sum()
sales_by_customer_type

Customer type
Member    678439.307517
Normal    655799.776779
Name: Total, dtype: float64

### Sales by Gender

In [9]:
# Sales by Gender
sales_by_gender = df.groupby('Gender')['Total'].sum()
sales_by_gender

Gender
Female    693557.342403
Male      640681.741893
Name: Total, dtype: float64

### Sales by Product Line

In [ ]:
# Sales by Product Line
sales_by_product_line = df.gropuby('Product line')['Total'].sum()
sales_by_product_line

Product line
Electronic accessories    224479.016791
Fashion accessories       224348.320192
Food and beverages        231945.379760
Health and beauty         203228.999517
Home and lifestyle        222514.143337
Sports and travel         227723.224699
Name: Total, dtype: float64

### Sales by Payment Method

In [11]:
# Sales by Payment Method
sales_by_payment = df.groupby('Payment')['Total'].sum()
sales_by_payment

Payment
Cash           463547.382733
Credit card    416288.569297
Ewallet        454403.132266
Name: Total, dtype: float64

### Average Rating by Product Line

In [ ]:
# Average Rating by Product Line
average_rating_by_product_line = df.groupby('Product line')['Rating'].mean()
average_rating_by_product_line

Product line
Electronic accessories    7.065445
Fashion accessories       7.176280
Food and beverages        7.262574
Health and beauty         7.149373
Home and lifestyle        6.981382
Sports and travel         7.056358
Name: Rating, dtype: float64

## 2. Time Series Analysis

### Monthly Sales Trend

In [14]:
# Monthly Sales Trend
monthly_sales_trend = df.resample('M', on='Date')['Total'].sum()
print(monthly_sales_trend)

Date
2019-01-31    86562.567000
2019-02-28    63169.743000
2019-03-31    72749.250000
2019-04-30     7957.624500
2019-05-31    12798.691500
                  ...
2025-08-31    13499.402326
2025-09-30    13762.824961
2025-10-31     9862.005577
2025-11-30     9615.251541
2025-12-31    11857.461421
Freq: ME, Name: Total, Length: 84, dtype: float64

C:\Users\Laptop\AppData\Local\Temp\ipykernel_12688\386840451.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sales_trend = df.resample('M', on='Date')['Total'].sum()

### Daily Sales Trend

In [ ]:
# Daily Sales Trend
daily_sales_trend = df.resample('D', on='Date')['Total'].sum()
daily_sales_trend

Date
2019-01-01    4745.181000
2019-01-02    2444.536500
2019-01-03    2634.366000
2019-01-04       0.000000
2019-01-05       0.000000
                 ...
2025-11-29       0.000000
2025-11-30       0.000000
2025-12-01    5183.083848
2025-12-02    2998.017450
2025-12-03    3676.360123
Freq: D, Name: Total, Length: 2529, dtype: float64

### Sales by Hour of the Day

In [15]:
# Sales by Hour
sales_by_hour = df.groupby('Hour')['Total'].sum()
sales_by_hour

Hour
10    129808.310505
11    125494.715543
12    107683.281037
13    143448.471830
14    127358.172257
15    128808.674572
16    104214.897884
17    100987.997622
18    107536.447988
19    164006.486848
20     94891.628212
Name: Total, dtype: float64

## 3. Customer Analysis

### Sales by Customer Type

In [16]:
# Sales by Customer Type
sales_by_customer_type = df.groupby('Customer type')['Total'].sum()
sales_by_customer_type

Customer type
Member    678439.307517
Normal    655799.776779
Name: Total, dtype: float64

### Sales by Gender

In [17]:
# Sales by Gender
sales_by_gender = df.groupby('Gender')['Total'].sum()
sales_by_gender

Gender
Female    693557.342403
Male      640681.741893
Name: Total, dtype: float64

### Average Purchase per Customer

In [18]:
# Average Purchase per Customer
average_purchase_per_customer = df['Total'].mean()
average_purchase_per_customer

np.float64(333.559771074045)

## 4. Product Analysis

### Sales by Product Line

In [19]:
# Sales by Product Line
sales_by_product_line = df.groupby('Product line')['Total'].sum()
sales_by_product_line

Product line
Electronic accessories    224479.016791
Fashion accessories       224348.320192
Food and beverages        231945.379760
Health and beauty         203228.999517
Home and lifestyle        222514.143337
Sports and travel         227723.224699
Name: Total, dtype: float64

### Most and Least Popular Products

In [16]:
# Most Popular Products
most_popular_products = df.groupby('Product line')['Quantity'].sum().sort_values(ascending=False)
most_popular_products

Product line
Electronic accessories    3886
Food and beverages        3807
Sports and travel         3679
Home and lifestyle        3645
Fashion accessories       3620
Health and beauty         3414
Name: Quantity, dtype: int64

In [34]:
# Least Popular Products
least_popular_products = df.groupby('Product line')['Quantity'].sum().sort_values(ascending=True)
least_popular_products

Product line
Health and beauty         854
Fashion accessories       902
Home and lifestyle        911
Sports and travel         920
Food and beverages        952
Electronic accessories    971
Name: Quantity, dtype: int64

### Revenue Contribution by Product Line

In [21]:
# Revenue Contribution
revenue_contribution = df.groupby('Product line')['Total'].sum() / total_sales * 100
revenue_contribution

Product line
Electronic accessories    16.824497
Fashion accessories       16.814702
Food and beverages        17.384094
Health and beauty         15.231828
Home and lifestyle        16.677232
Sports and travel         17.067648
Name: Total, dtype: float64

## 5. Payment Analysis

### Sales by Payment Method

In [36]:
# Sales by Payment Method
sales_by_payment_method = df.groupby('Payment')['Total'].sum()
sales_by_payment_method

Payment
Cash           112206.570
Credit card    100767.072
Ewallet        109993.107
Name: Total, dtype: float64

## 6. Rating Analysis

### Average Rating by Product Line

In [37]:
# Average Rating by Product Line
average_rating_by_product_line = df.groupby('Product line')['Rating'].mean()
average_rating_by_product_line

Product line
Electronic accessories    6.924706
Fashion accessories       7.029213
Food and beverages        7.113218
Health and beauty         7.003289
Home and lifestyle        6.837500
Sports and travel         6.916265
Name: Rating, dtype: float64

### Rating Distribution

In [38]:
# Rating Distribution
rating_distribution = df['Rating'].value_counts()
rating_distribution

Rating
6.0     26
6.6     24
4.2     22
9.5     22
6.5     21
        ..
4.0     11
5.3     11
8.3     11
4.6      8
10.0     5
Name: count, Length: 61, dtype: int64

## 7. Branch Analysis

### Branch Performance

In [39]:
# Branch Performance
branch_performance = df.groupby('Branch').agg({'Total': ['sum', 'mean', 'count']})
branch_performance

              Total
                sum        mean count
Branch
A       106200.3705  312.354031   340
B       106197.6720  319.872506   332
C       110568.7065  337.099715   328

## 8. Profit Analysis

### Gross Profit and Profit Margin

In [40]:
# Gross Profit
df['Gross Profit'] = df['Total'] - df['cogs']
# Profit Margin
df['Profit Margin'] = (df['Gross Profit'] / df['Total']) * 100
gross_profit = df['Gross Profit'].sum()
profit_margin = df['Profit Margin'].mean()
gross_profit, profit_margin

(15379.368999999999, 4.761904761904762)